(source gnu)
(source melpa)

;; cask
(depends-on "cask")
(depends-on "pallet")

;; basics
(depends-on "bind-key")
(depends-on "company")
(depends-on "expand-region")
(depends-on "exec-path-from-shell")
(depends-on "multiple-cursors")
(depends-on "projectile")
(depends-on "use-package")
(depends-on "smartparens")
(depends-on "smartrep")
(depends-on "yasnippet")

;; Appearance
(depends-on "all-the-icons")
(depends-on "helm")
(depends-on "idle-highlight-mode")
(depends-on "highlight-indentation")
(depends-on "indent-guide")
(depends-on "popwin")
(depends-on "powerline")
(depends-on "rainbow-delimiters")

;; flycheck
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "flycheck-rust")

;; Python
(depends-on "company-jedi")
(depends-on "jedi-core")
(depends-on "virtualenvwrapper")
(depends-on "auto-virtualenvwrapper")

;; Rust
(depends-on "racer")
(depends-on "rust-mode")

;; Web
(depends-on "emmet-mode")
(depends-on "web-mode")

;; language modes
(depends-on "lua-mode")
(depends-on "markdown-mode")

;; others
(depends-on "magit")
(depends-on "neotree")
(depends-on "multi-term")
(depends-on "shell-pop")
