(source gnu)
(source melpa)

;; cask
(depends-on "cask")
(depends-on "pallet")

;; basics
(depends-on "bind-key")
(depends-on "company")
(depends-on "expand-region")
(depends-on "exec-path-from-shell")
(depends-on "multiple-cursors")
(depends-on "projectile")
(depends-on "use-package")
(depends-on "smartparens")
(depends-on "smartrep")
(depends-on "yasnippet")

;; Appearance
(depends-on "all-the-icons")
(depends-on "swiper")
(depends-on "counsel")
(depends-on "idle-highlight-mode")
(depends-on "highlight-indentation")
(depends-on "indent-guide")
(depends-on "popwin")
(depends-on "powerline")
(depends-on "rainbow-delimiters")
(depends-on "nord-theme")
(depends-on "treemacs")

;; flycheck
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "flycheck-rust")

;; Web
(depends-on "emmet-mode")
(depends-on "web-mode")

;; typescript
(depends-on "tide")
(depends-on "typescript-mode")

;; others
(depends-on "magit")
(depends-on "multi-term")
(depends-on "shell-pop")
(depends-on "markdown-mode")
